tasks:
  - init: git remote set-url origin git@github.com:AishwaryaTest002/Pass1-2-3-FizzBuzz.git && sed "s/\r$//" commit-command.sh | bash && gp open README.md
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - Revaturepro-non-prod.revature-labs-non-prod